spring.application.name=HealthTracking

spring.datasource.url=jdbc:sqlserver://localhost:1440;databaseName=health-tracking-db;encrypt=false
spring.datasource.username=burak
spring.datasource.password=Bur@kCan_2024
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

jwt-config.secretKey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt-config.jwtExpiration=86400000

nutrition-config.baseUrl=https://world.openfoodfacts.org/cgi/search.pl

llm-config.apiKey=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
llm-config.model=openai/gpt-4o-mini
llm-config.apiUrl=https://openrouter.ai/api/v1/chat/completions

job-config.dailyRecommendation=0 59 23 * * ?
job-config.midDayReminder=0 0 12 * * ?
job-config.weeklyReports=0 0 23 ? * SUN

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

queue-config.reportQueue=weekly-report-queue
