spring.application.name=HealthTracking

spring.datasource.url=jdbc:sqlserver://localhost:1440;databaseName=health-tracking-db;encrypt=false
spring.datasource.username=burak
spring.datasource.password=Bur@kCan_2024
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
#spring.sql.init.data-locations=classpath:data.sql

jwt.secret.key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

address.base.url=https://world.openfoodfacts.org/cgi/search.pl

llm.api.key=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
llm.model=openai/gpt-4o-mini
llm.url=https://openrouter.ai/api/v1/chat/completions